// Generated by tools/generate-flight-cues.py; measured local clip lengths in seconds.
export const boardingLengths={"cloudline-tokyo-boarding": 17.18, "cloudline-bangkok-boarding": 17.17, "cloudline-paris-boarding": 17.09, "blue-hour-tokyo-boarding": 16.56, "blue-hour-bangkok-boarding": 16.61, "blue-hour-paris-boarding": 16.53};
export const captainLengths={"cloudline": 4.862666666666667, "blue-hour": 5.275333333333333};
